### PR TITLE
Bugfix: accept genbook treekeys in the same format as libsword does and fix key mapping in SwordGenBook.java (getName -> getOsisRef) 

### PR DESCRIPTION
**Pull request by tuomas2**
Fixes https://github.com/mjdenham/and-bible/issues/23

### CODE REVIEW

**Comment by tuomas2** [comment]
From libsword source I (treekeyidx.cpp:517 i.e. TreeKeyIdx.setText()) can be seen that the current sword implementation requires key in slash format (i.e. "ESVN_articles:Book_introductions/Introduction_to_Genesis/Genesis_and_Science" instead of dot format "ESVN_articles:Book_introductions.Introduction_to_Genesis.Genesis_and_Science"). If I understand correctly, libsword is the reference implementation which jsword should conform to. Or is genbook osisRef syntax defined by OSIS standard? Not if I see it correctly. Now the behaviour should be the same as in libsword.

**Comment by dmsmith** [comment]
JSword comforms to the OSIS standard. / is not allowed in an osisRef. If libsword uses / as an internal representation it is no problem, but if it uses it in modules, then it is a problem that they need to fix.

— DM Smith

**Comment by tuomas2** [comment]
Fixed PR according to OSIS standard. I'm investigating libsword implementation a bit further and will propose a fix for that.

**Comment by tuomas2** [comment]
@dmsmith There is discussion about this topic on  http://www.crosswire.org/pipermail/sword-devel/2015-June/042195.html. I would like to suggest that we break OSIS for now and allow '/' because otherwise genbooks links can't be functional on both libsword and jsword and this would make them incompatible. Do you agree? If so, I will revert my pull request back to what I suggested earlier.

**Comment by tuomas2** [comment]
Now after some investigations, it seems that my original issue (internal links with '/' separator in osisRefs not working in genbooks) is fixed by some recent change in jsword. 

When I reported the bug, I was using the version that was bundled in the latest stable version of AndBible. Now getName() return full reference with '/' as separator instead of giving only name of the leaf node. Thus I'm not quite sure if this fix is necessary at all.

**Comment by tuomas2** [comment]
Added another small fix to this pull request to allow whitespaces in genbook osisIDs. OSIS spec does not prevent them and they are often used.

**Comment by tuomas2** [comment]
@mjdenham could you take a look at this, and give your thoughts. Especially I would like to see this patch in And bible. ;)

**Comment by dmsmith** [comment]
Thanks!

**Pull request merged**
